local __FILE__ = select(1, ...) or ""
local __PACKAGE__ = string.gsub(__FILE__, "[^.]+$", "")
SkillDevKit = {}

require(__PACKAGE__ .. "misc")
require(__PACKAGE__ .. "motions")
require(__PACKAGE__ .. "locators")
require(__PACKAGE__ .. "recorder")
require(__PACKAGE__ .. "unit_loader")
require(__PACKAGE__ .. "unit_iterators")
require(__PACKAGE__ .. "formulas")
require(__PACKAGE__ .. "health_ops")
require(__PACKAGE__ .. "anger_ops")
require(__PACKAGE__ .. "buff_ops")
require(__PACKAGE__ .. "sp_ops")
require(__PACKAGE__ .. "schedule")
require(__PACKAGE__ .. "unit_ops")
require(__PACKAGE__ .. "team_ops")
require(__PACKAGE__ .. "trap_ops")
require(__PACKAGE__ .. "card_ops")
