require("dm.battle.view.interpreter.BattleInterpreter")
require("dm.battle.view.interpreter.UnitTLInterpreter")
require("dm.battle.view.interpreter.PlayerTLInterpreter")
require("dm.battle.view.interpreter.MainTLInterpreter")
require("dm.battle.view.interpreter.GuideTLInterpreter")
require("dm.battle.view.interpreter.BFieldTLInterpreter")
