cc = cc or {}
cc.SPRITE_INDEX_NOT_INITIALIZED = 4294967295.0
cc.TMX_ORIENTATION_HEX = 1
cc.TMX_ORIENTATION_ISO = 2
cc.TMX_ORIENTATION_ORTHO = 0
cc.Z_COMPRESSION_BZIP2 = 1
cc.Z_COMPRESSION_GZIP = 2
cc.Z_COMPRESSION_NONE = 3
cc.Z_COMPRESSION_ZLIB = 0
cc.BLEND_DST = 771
cc.BLEND_SRC = 1
cc.DIRECTOR_IOS_USE_BACKGROUND_THREAD = 0
cc.DIRECTOR_MAC_THREAD = 0
cc.DIRECTOR_STATS_INTERVAL = 0.1
cc.ENABLE_BOX2_D_INTEGRATION = 0
cc.ENABLE_DEPRECATED = 1
cc.ENABLE_GL_STATE_CACHE = 1
cc.ENABLE_PROFILERS = 0
cc.ENABLE_STACKABLE_ACTIONS = 1
cc.FIX_ARTIFACTS_BY_STRECHING_TEXEL = 0
cc.GL_ALL = 0
cc.LABELATLAS_DEBUG_DRAW = 0
cc.LABELBMFONT_DEBUG_DRAW = 0
cc.MAC_USE_DISPLAY_LINK_THREAD = 0
cc.MAC_USE_MAIN_THREAD = 2
cc.MAC_USE_OWN_THREAD = 1
cc.NODE_RENDER_SUBPIXEL = 1
cc.PVRMIPMAP_MAX = 16
cc.SPRITEBATCHNODE_RENDER_SUBPIXEL = 1
cc.SPRITE_DEBUG_DRAW = 0
cc.TEXTURE_ATLAS_USE_TRIANGLE_STRIP = 0
cc.TEXTURE_ATLAS_USE_VAO = 1
cc.USE_L_A88_LABELS = 1
cc.ACTION_TAG_INVALID = -1
cc.DEVICE_MAC = 6
cc.DEVICE_MAC_RETINA_DISPLAY = 7
cc.DEVICEI_PAD = 4
cc.DEVICEI_PAD_RETINA_DISPLAY = 5
cc.DEVICEI_PHONE = 0
cc.DEVICEI_PHONE5 = 2
cc.DEVICEI_PHONE5_RETINA_DISPLAY = 3
cc.DEVICEI_PHONE_RETINA_DISPLAY = 1
cc.DIRECTOR_PROJECTION2_D = 0
cc.DIRECTOR_PROJECTION3_D = 1
cc.DIRECTOR_PROJECTION_CUSTOM = 2
cc.DIRECTOR_PROJECTION_DEFAULT = 1
cc.FILE_UTILS_SEARCH_DIRECTORY_MODE = 1
cc.FILE_UTILS_SEARCH_SUFFIX_MODE = 0
cc.FLIPED_ALL = 3758096384.0
cc.FLIPPED_MASK = 536870911
cc.IMAGE_FORMAT_JPEG = 0
cc.IMAGE_FORMAT_PNG = 1
cc.ITEM_SIZE = 32
cc.LABEL_AUTOMATIC_WIDTH = -1
cc.LINE_BREAK_MODE_CHARACTER_WRAP = 1
cc.LINE_BREAK_MODE_CLIP = 2
cc.LINE_BREAK_MODE_HEAD_TRUNCATION = 3
cc.LINE_BREAK_MODE_MIDDLE_TRUNCATION = 5
cc.LINE_BREAK_MODE_TAIL_TRUNCATION = 4
cc.LINE_BREAK_MODE_WORD_WRAP = 0
cc.MAC_VERSION_10_6 = 168165376
cc.MAC_VERSION_10_7 = 168230912
cc.MAC_VERSION_10_8 = 168296448
cc.MENU_HANDLER_PRIORITY = -128
cc.MENU_STATE_TRACKING_TOUCH = 1
cc.MENU_STATE_WAITING = 0
cc.NODE_TAG_INVALID = -1
cc.PARTICLE_DURATION_INFINITY = -1
cc.PARTICLE_MODE_GRAVITY = 0
cc.PARTICLE_MODE_RADIUS = 1
cc.PARTICLE_START_RADIUS_EQUAL_TO_END_RADIUS = -1
cc.PARTICLE_START_SIZE_EQUAL_TO_END_SIZE = -1
cc.POSITION_TYPE_FREE = 0
cc.POSITION_TYPE_GROUPED = 2
cc.POSITION_TYPE_RELATIVE = 1
cc.PRIORITY_NON_SYSTEM_MIN = -2147483647
cc.PRIORITY_SYSTEM = -2147483648
cc.PROGRESS_TIMER_TYPE_BAR = 1
cc.PROGRESS_TIMER_TYPE_RADIAL = 0
cc.REPEAT_FOREVER = 4294967294.0
cc.RESOLUTION_MAC = 1
cc.RESOLUTION_MAC_RETINA_DISPLAY = 2
cc.RESOLUTION_UNKNOWN = 0
cc.TMX_TILE_DIAGONAL_FLAG = 536870912
cc.TMX_TILE_HORIZONTAL_FLAG = 2147483648.0
cc.TMX_TILE_VERTICAL_FLAG = 1073741824
cc.TEXT_ALIGNMENT_CENTER = 1
cc.TEXT_ALIGNMENT_LEFT = 0
cc.TEXT_ALIGNMENT_RIGHT = 2
cc.TEXTURE2_D_PIXEL_FORMAT_AUTO = 0
cc.TEXTURE2_D_PIXEL_FORMAT_BGR_A8888 = 1
cc.TEXTURE2_D_PIXEL_FORMAT_RGB_A8888 = 2
cc.TEXTURE2_D_PIXEL_FORMAT_RG_B888 = 3
cc.TEXTURE2_D_PIXEL_FORMAT_RG_B565 = 4
cc.TEXTURE2_D_PIXEL_FORMAT_A8 = 5
cc.TEXTURE2_D_PIXEL_FORMAT_I8 = 6
cc.TEXTURE2_D_PIXEL_FORMAT_A_I88 = 7
cc.TEXTURE2_D_PIXEL_FORMAT_RGB_A4444 = 8
cc.TEXTURE2_D_PIXEL_FORMAT_RGB5_A1 = 9
cc.TEXTURE2_D_PIXEL_FORMAT_PVRTC4 = 10
cc.TEXTURE2_D_PIXEL_FORMAT_PVRTC4A = 11
cc.TEXTURE2_D_PIXEL_FORMAT_PVRTC2 = 12
cc.TEXTURE2_D_PIXEL_FORMAT_PVRTC2A = 13
cc.TEXTURE2_D_PIXEL_FORMAT_ETC = 14
cc.TEXTURE2_D_PIXEL_FORMAT_S3TC_DXT1 = 15
cc.TEXTURE2_D_PIXEL_FORMAT_S3TC_DXT3 = 16
cc.TEXTURE2_D_PIXEL_FORMAT_S3TC_DXT5 = 17
cc.TEXTURE2_D_PIXEL_FORMAT_DEFAULT = 0
cc.TOUCHES_ALL_AT_ONCE = 0
cc.TOUCHES_ONE_BY_ONE = 1
cc.TRANSITION_ORIENTATION_DOWN_OVER = 1
cc.TRANSITION_ORIENTATION_LEFT_OVER = 0
cc.TRANSITION_ORIENTATION_RIGHT_OVER = 1
cc.TRANSITION_ORIENTATION_UP_OVER = 0
cc.UNIFORM_COS_TIME = 5
cc.UNIFORM_MV_MATRIX = 1
cc.UNIFORM_MVP_MATRIX = 2
cc.UNIFORM_P_MATRIX = 0
cc.UNIFORM_RANDOM01 = 6
cc.UNIFORM_SAMPLER = 7
cc.UNIFORM_SIN_TIME = 4
cc.UNIFORM_TIME = 3
cc.UNIFORM_MAX = 8
cc.VERTEX_ATTRIB_FLAG_COLOR = 2
cc.VERTEX_ATTRIB_FLAG_NONE = 0
cc.VERTEX_ATTRIB_FLAG_POS_COLOR_TEX = 7
cc.VERTEX_ATTRIB_FLAG_POSITION = 1
cc.VERTEX_ATTRIB_FLAG_TEX_COORDS = 4
cc.VERTEX_ATTRIB_COLOR = 1
cc.VERTEX_ATTRIB_MAX = 3
cc.VERTEX_ATTRIB_POSITION = 0
cc.VERTEX_ATTRIB_TEX_COORD = 2
cc.VERTEX_ATTRIB_TEX_COORDS = 2
cc.VERTICAL_TEXT_ALIGNMENT_BOTTOM = 2
cc.VERTICAL_TEXT_ALIGNMENT_CENTER = 1
cc.VERTICAL_TEXT_ALIGNMENT_TOP = 0
cc.OS_VERSION_4_0 = 67108864
cc.OS_VERSION_4_0_1 = 67109120
cc.OS_VERSION_4_1 = 67174400
cc.OS_VERSION_4_2 = 67239936
cc.OS_VERSION_4_2_1 = 67240192
cc.OS_VERSION_4_3 = 67305472
cc.OS_VERSION_4_3_1 = 67305728
cc.OS_VERSION_4_3_2 = 67305984
cc.OS_VERSION_4_3_3 = 67306240
cc.OS_VERSION_4_3_4 = 67306496
cc.OS_VERSION_4_3_5 = 67306752
cc.OS_VERSION_5_0 = 83886080
cc.OS_VERSION_5_0_1 = 83886336
cc.OS_VERSION_5_1_0 = 83951616
cc.OS_VERSION_6_0_0 = 100663296
cc.ANIMATION_FRAME_DISPLAYED_NOTIFICATION = "CCAnimationFrameDisplayedNotification"
cc.CHIPMUNK_IMPORT = "chipmunk.h"
cc.ATTRIBUTE_NAME_COLOR = "a_color"
cc.ATTRIBUTE_NAME_POSITION = "a_position"
cc.ATTRIBUTE_NAME_TEX_COORD = "a_texCoord"
cc.SHADER_POSITION_COLOR = "ShaderPositionColor"
cc.SHADER_POSITION_LENGTH_TEXURE_COLOR = "ShaderPositionLengthTextureColor"
cc.SHADER_POSITION_TEXTURE = "ShaderPositionTexture"
cc.SHADER_POSITION_TEXTURE_A8_COLOR = "ShaderPositionTextureA8Color"
cc.SHADER_POSITION_TEXTURE_COLOR = "ShaderPositionTextureColor"
cc.SHADER_POSITION_TEXTURE_COLOR_ALPHA_TEST = "ShaderPositionTextureColorAlphaTest"
cc.SHADER_POSITION_TEXTURE_U_COLOR = "ShaderPositionTexture_uColor"
cc.SHADER_POSITION_U_COLOR = "ShaderPosition_uColor"
cc.UNIFORM_ALPHA_TEST_VALUE_S = "CC_AlphaValue"
cc.UNIFORM_COS_TIME_S = "CC_CosTime"
cc.UNIFORM_MV_MATRIX_S = "CC_MVMatrix"
cc.UNIFORM_MVP_MATRIX_S = "CC_MVPMatrix"
cc.UNIFORM_P_MATRIX_S = "CC_PMatrix"
cc.UNIFORM_RANDOM01_S = "CC_Random01"
cc.UNIFORM_SAMPLER_S = "CC_Texture0"
cc.UNIFORM_SIN_TIME_S = "CC_SinTime"
cc.UNIFORM_TIME_S = "CC_Time"
cc.PLATFORM_OS_WINDOWS = 0
cc.PLATFORM_OS_LINUX = 1
cc.PLATFORM_OS_MAC = 2
cc.PLATFORM_OS_ANDROID = 3
cc.PLATFORM_OS_IPHONE = 4
cc.PLATFORM_OS_IPAD = 5
cc.PLATFORM_OS_BLACKBERRY = 6
cc.PLATFORM_OS_NACL = 7
cc.PLATFORM_OS_EMSCRIPTEN = 8
cc.PLATFORM_OS_TIZEN = 9
cc.PLATFORM_OS_WINRT = 10
cc.PLATFORM_OS_WP8 = 11
cc.LANGUAGE_ENGLISH = 0
cc.LANGUAGE_CHINESE = 1
cc.LANGUAGE_FRENCH = 2
cc.LANGUAGE_ITALIAN = 3
cc.LANGUAGE_GERMAN = 4
cc.LANGUAGE_SPANISH = 5
cc.LANGUAGE_DUTCH = 6
cc.LANGUAGE_RUSSIAN = 7
cc.LANGUAGE_KOREAN = 8
cc.LANGUAGE_JAPANESE = 9
cc.LANGUAGE_HUNGARIAN = 10
cc.LANGUAGE_PORTUGUESE = 11
cc.LANGUAGE_ARABIC = 12
cc.LANGUAGE_THAI = 19
cc.NODE_ON_ENTER = 0
cc.NODE_ON_EXIT = 1
cc.NODE_ON_ENTER_TRANSITION_DID_FINISH = 2
cc.NODE_ON_EXIT_TRANSITION_DID_START = 3
cc.NODE_ON_CLEAN_UP = 4

local function moduleType(a)
	return a * 64
end

cc.Handler = cc.Handler or {}
cc.Handler.NODE = moduleType(0)
cc.Handler.MENU_CLICKED = moduleType(0) + 1
cc.Handler.CALLFUNC = moduleType(0) + 2
cc.Handler.SCHEDULE = moduleType(0) + 3
cc.Handler.TOUCHES = moduleType(0) + 4
cc.Handler.KEYPAD = moduleType(0) + 5
cc.Handler.ACCELEROMETER = moduleType(0) + 6
cc.Handler.CONTROL_TOUCH_DOWN = moduleType(1)
cc.Handler.CONTROL_TOUCH_DRAG_INSIDE = moduleType(1) + 1
cc.Handler.CONTROL_TOUCH_DRAG_OUTSIDE = moduleType(1) + 2
cc.Handler.CONTROL_TOUCH_DRAG_ENTER = moduleType(1) + 3
cc.Handler.CONTROL_TOUCH_DRAG_EXIT = moduleType(1) + 4
cc.Handler.CONTROL_TOUCH_UP_INSIDE = moduleType(1) + 5
cc.Handler.CONTROL_TOUCH_UP_OUTSIDE = moduleType(1) + 6
cc.Handler.CONTROL_TOUCH_UP_CANCEL = moduleType(1) + 7
cc.Handler.CONTROL_VALUE_CHANGED = moduleType(1) + 8
cc.Handler.WEBSOCKET_OPEN = moduleType(2)
cc.Handler.WEBSOCKET_MESSAGE = moduleType(2) + 1
cc.Handler.WEBSOCKET_CLOSE = moduleType(2) + 2
cc.Handler.WEBSOCKET_ERROR = moduleType(2) + 3
cc.Handler.GL_NODE_DRAW = moduleType(3)
cc.Handler.SCROLLVIEW_SCROLL = moduleType(4)
cc.Handler.SCROLLVIEW_ZOOM = moduleType(4) + 1
cc.Handler.TABLECELL_TOUCHED = moduleType(5)
cc.Handler.TABLECELL_HIGHLIGHT = moduleType(5) + 1
cc.Handler.TABLECELL_UNHIGHLIGHT = moduleType(5) + 2
cc.Handler.TABLECELL_WILL_RECYCLE = moduleType(5) + 3
cc.Handler.TABLECELL_SIZE_FOR_INDEX = moduleType(5) + 4
cc.Handler.TABLECELL_AT_INDEX = moduleType(5) + 5
cc.Handler.TABLECELL_ADDED = moduleType(5) + 6
cc.Handler.TABLEVIEW_NUMS_OF_CELLS = moduleType(5) + 7
cc.Handler.HTTPREQUEST_STATE_CHANGE = moduleType(6)
cc.Handler.ASSETSMANAGER_PROGRESS = moduleType(7)
cc.Handler.ASSETSMANAGER_SUCCESS = moduleType(7) + 1
cc.Handler.ASSETSMANAGER_ERROR = moduleType(7) + 2
cc.Handler.STUDIO_EVENT_LISTENER = moduleType(8)
cc.Handler.ARMATURE_EVENT = moduleType(9)
cc.Handler.EVENT_ACC = moduleType(10)
cc.Handler.EVENT_CUSTIOM = moduleType(11)
cc.Handler.EVENT_KEYBOARD_PRESSED = moduleType(12)
cc.Handler.EVENT_KEYBOARD_RELEASED = moduleType(12) + 1
cc.Handler.EVENT_TOUCH_BEGAN = moduleType(13)
cc.Handler.EVENT_TOUCH_MOVED = moduleType(13) + 1
cc.Handler.EVENT_TOUCH_ENDED = moduleType(13) + 2
cc.Handler.EVENT_TOUCH_CANCELLED = moduleType(13) + 3
cc.Handler.EVENT_TOUCHES_BEGAN = moduleType(13) + 4
cc.Handler.EVENT_TOUCHES_MOVED = moduleType(13) + 5
cc.Handler.EVENT_TOUCHES_ENDED = moduleType(13) + 6
cc.Handler.EVENT_TOUCHES_CANCELLED = moduleType(13) + 7
cc.Handler.EVENT_MOUSE_DOWN = moduleType(13) + 8
cc.Handler.EVENT_MOUSE_UP = moduleType(13) + 9
cc.Handler.EVENT_MOUSE_MOVE = moduleType(13) + 10
cc.Handler.EVENT_MOUSE_SCROLL = moduleType(13) + 11
cc.Handler.EVENT_SPINE = moduleType(14)
cc.Handler.EVENT_PHYSICS_CONTACT_BEGIN = moduleType(15)
cc.Handler.EVENT_PHYSICS_CONTACT_PRESOLVE = moduleType(15) + 1
cc.Handler.EVENT_PHYSICS_CONTACT_POSTSOLVE = moduleType(15) + 2
cc.Handler.EVENT_PHYSICS_CONTACT_SEPARATE = moduleType(15) + 3
cc.Handler.EVENT_FOCUS = moduleType(16)
cc.Handler.EVENT_CONTROLLER_CONNECTED = moduleType(17)
cc.Handler.EVENT_CONTROLLER_DISCONNECTED = moduleType(17) + 1
cc.Handler.EVENT_CONTROLLER_KEYDOWN = moduleType(17) + 2
cc.Handler.EVENT_CONTROLLER_KEYUP = moduleType(17) + 3
cc.Handler.EVENT_CONTROLLER_KEYREPEAT = moduleType(17) + 4
cc.Handler.EVENT_CONTROLLER_AXIS = moduleType(17) + 5
cc.Handler.EVENT_SPINE_ANIMATION_START = moduleType(18)
cc.Handler.EVENT_SPINE_ANIMATION_INTERRUPT = moduleType(18) + 1
cc.Handler.EVENT_SPINE_ANIMATION_END = moduleType(18) + 2
cc.Handler.EVENT_SPINE_ANIMATION_COMPLETE = moduleType(18) + 3
cc.Handler.EVENT_SPINE_ANIMATION_DISPOSE = moduleType(18) + 4
cc.Handler.EVENT_SPINE_ANIMATION_EVENT = moduleType(18) + 5
cc.Handler.EVENT_SNEAKYJOYSTICK = moduleType(19)
cc.SCROLLVIEW_SCRIPT_SCROLL = moduleType(4)
cc.SCROLLVIEW_SCRIPT_ZOOM = moduleType(4) + 1
cc.TABLECELL_TOUCHED = moduleType(5) + 0
cc.TABLECELL_HIGH_LIGHT = moduleType(5) + 1
cc.TABLECELL_UNHIGH_LIGHT = moduleType(5) + 2
cc.TABLECELL_WILL_RECYCLE = moduleType(5) + 3
cc.TABLECELL_SIZE_FOR_INDEX = moduleType(5) + 4
cc.TABLECELL_SIZE_AT_INDEX = moduleType(5) + 5
cc.TABLECELL_ADDED = moduleType(5) + 6
cc.NUMBER_OF_CELLS_IN_TABLEVIEW = moduleType(5) + 7
cc.EVENT_UNKNOWN = 0
cc.EVENT_TOUCH_ONE_BY_ONE = 1
cc.EVENT_TOUCH_ALL_AT_ONCE = 2
cc.EVENT_KEYBOARD = 3
cc.EVENT_MOUSE = 4
cc.EVENT_ACCELERATION = 5
cc.EVENT_CUSTOM = 6
cc.PHYSICSSHAPE_MATERIAL_DEFAULT = {
	restitution = 0.5,
	density = 0,
	friction = 0.5
}
cc.PHYSICSBODY_MATERIAL_DEFAULT = {
	restitution = 0.5,
	density = 0.1,
	friction = 0.5
}
cc.GLYPHCOLLECTION_DYNAMIC = 0
cc.GLYPHCOLLECTION_NEHE = 1
cc.GLYPHCOLLECTION_ASCII = 2
cc.GLYPHCOLLECTION_CUSTOM = 3
cc.ResolutionPolicy = {
	FIXED_HEIGHT = 3,
	SHOW_ALL = 2,
	NO_BORDER = 1,
	EXACT_FIT = 0,
	FIXED_WIDTH = 4,
	UNKNOWN = 5
}
cc.LabelEffect = {
	GLOW = 3,
	SHADOW = 2,
	NORMAL = 0,
	OUTLINE = 1
}
cc.LabelOverflow = {
	CLAMP = 1,
	SHRINK = 2,
	RESIZE_HEIGHT = 3,
	NONE = 0
}
cc.KeyCodeKey = {
	"KEY_NONE",
	"KEY_PAUSE",
	"KEY_SCROLL_LOCK",
	"KEY_PRINT",
	"KEY_SYSREQ",
	"KEY_BREAK",
	"KEY_ESCAPE",
	"KEY_BACKSPACE",
	"KEY_TAB",
	"KEY_BACK_TAB",
	"KEY_RETURN",
	"KEY_CAPS_LOCK",
	"KEY_SHIFT",
	"KEY_RIGHT_SHIFT",
	"KEY_CTRL",
	"KEY_RIGHT_CTRL",
	"KEY_ALT",
	"KEY_RIGHT_ALT",
	"KEY_MENU",
	"KEY_HYPER",
	"KEY_INSERT",
	"KEY_HOME",
	"KEY_PG_UP",
	"KEY_DELETE",
	"KEY_END",
	"KEY_PG_DOWN",
	"KEY_LEFT_ARROW",
	"KEY_RIGHT_ARROW",
	"KEY_UP_ARROW",
	"KEY_DOWN_ARROW",
	"KEY_NUM_LOCK",
	"KEY_KP_PLUS",
	"KEY_KP_MINUS",
	"KEY_KP_MULTIPLY",
	"KEY_KP_DIVIDE",
	"KEY_KP_ENTER",
	"KEY_KP_HOME",
	"KEY_KP_UP",
	"KEY_KP_PG_UP",
	"KEY_KP_LEFT",
	"KEY_KP_FIVE",
	"KEY_KP_RIGHT",
	"KEY_KP_END",
	"KEY_KP_DOWN",
	"KEY_KP_PG_DOWN",
	"KEY_KP_INSERT",
	"KEY_KP_DELETE",
	"KEY_F1",
	"KEY_F2",
	"KEY_F3",
	"KEY_F4",
	"KEY_F5",
	"KEY_F6",
	"KEY_F7",
	"KEY_F8",
	"KEY_F9",
	"KEY_F10",
	"KEY_F11",
	"KEY_F12",
	"KEY_SPACE",
	"KEY_EXCLAM",
	"KEY_QUOTE",
	"KEY_NUMBER",
	"KEY_DOLLAR",
	"KEY_PERCENT",
	"KEY_CIRCUMFLEX",
	"KEY_AMPERSAND",
	"KEY_APOSTROPHE",
	"KEY_LEFT_PARENTHESIS",
	"KEY_RIGHT_PARENTHESIS",
	"KEY_ASTERISK",
	"KEY_PLUS",
	"KEY_COMMA",
	"KEY_MINUS",
	"KEY_PERIOD",
	"KEY_SLASH",
	"KEY_0",
	"KEY_1",
	"KEY_2",
	"KEY_3",
	"KEY_4",
	"KEY_5",
	"KEY_6",
	"KEY_7",
	"KEY_8",
	"KEY_9",
	"KEY_COLON",
	"KEY_SEMICOLON",
	"KEY_LESS_THAN",
	"KEY_EQUAL",
	"KEY_GREATER_THAN",
	"KEY_QUESTION",
	"KEY_AT",
	"KEY_CAPITAL_A",
	"KEY_CAPITAL_B",
	"KEY_CAPITAL_C",
	"KEY_CAPITAL_D",
	"KEY_CAPITAL_E",
	"KEY_CAPITAL_F",
	"KEY_CAPITAL_G",
	"KEY_CAPITAL_H",
	"KEY_CAPITAL_I",
	"KEY_CAPITAL_J",
	"KEY_CAPITAL_K",
	"KEY_CAPITAL_L",
	"KEY_CAPITAL_M",
	"KEY_CAPITAL_N",
	"KEY_CAPITAL_O",
	"KEY_CAPITAL_P",
	"KEY_CAPITAL_Q",
	"KEY_CAPITAL_R",
	"KEY_CAPITAL_S",
	"KEY_CAPITAL_T",
	"KEY_CAPITAL_U",
	"KEY_CAPITAL_V",
	"KEY_CAPITAL_W",
	"KEY_CAPITAL_X",
	"KEY_CAPITAL_Y",
	"KEY_CAPITAL_Z",
	"KEY_LEFT_BRACKET",
	"KEY_BACK_SLASH",
	"KEY_RIGHT_BRACKET",
	"KEY_UNDERSCORE",
	"KEY_GRAVE",
	"KEY_A",
	"KEY_B",
	"KEY_C",
	"KEY_D",
	"KEY_E",
	"KEY_F",
	"KEY_G",
	"KEY_H",
	"KEY_I",
	"KEY_J",
	"KEY_K",
	"KEY_L",
	"KEY_M",
	"KEY_N",
	"KEY_O",
	"KEY_P",
	"KEY_Q",
	"KEY_R",
	"KEY_S",
	"KEY_T",
	"KEY_U",
	"KEY_V",
	"KEY_W",
	"KEY_X",
	"KEY_Y",
	"KEY_Z",
	"KEY_LEFT_BRACE",
	"KEY_BAR",
	"KEY_RIGHT_BRACE",
	"KEY_TILDE",
	"KEY_EURO",
	"KEY_POUND",
	"KEY_YEN",
	"KEY_MIDDLE_DOT",
	"KEY_SEARCH",
	"KEY_DPAD_LEFT",
	"KEY_DPAD_RIGHT",
	"KEY_DPAD_UP",
	"KEY_DPAD_DOWN",
	"KEY_DPAD_CENTER",
	"KEY_ENTER",
	"KEY_PLAY"
}
cc.KeyCode = {}

for k, v in ipairs(cc.KeyCodeKey) do
	cc.KeyCode[v] = k - 1
end

cc.KeyCode.KEY_BACK = cc.KeyCode.KEY_ESCAPE
cc.KeyCode.KEY_LEFT_SHIFT = cc.KeyCode.KEY_SHIFT
cc.KeyCode.KEY_LEFT_CTRL = cc.KeyCode.KEY_CTRL
cc.KeyCode.KEY_LEFT_ALT = cc.KeyCode.KEY_ALT
cc.EventAssetsManagerEx = {
	EventCode = {
		UPDATE_PROGRESSION = 5,
		ERROR_NO_LOCAL_MANIFEST = 0,
		ERROR_PARSE_MANIFEST = 2,
		UPDATE_FAILED = 9,
		UPDATE_FINISHED = 8,
		ERROR_DECOMPRESS = 10,
		ERROR_DOWNLOAD_MANIFEST = 1,
		ERROR_UPDATING = 7,
		ALREADY_UP_TO_DATE = 4,
		ASSET_UPDATED = 6,
		NEW_VERSION_FOUND = 3
	}
}
cc.AssetsManagerExStatic = {
	VERSION_ID = "@version",
	MANIFEST_ID = "@manifest"
}
cc.EventCode = {
	ENDED = 2,
	BEGAN = 0,
	CANCELLED = 3,
	MOVED = 1
}
cc.DIRECTOR_PROJECTION_2D = 0
cc.DIRECTOR_PROJECTION_3D = 1
cc.ConfigType = {
	COCOSTUDIO = 1,
	NONE = 0
}
cc.AUDIO_INVAILD_ID = -1
cc.AUDIO_TIME_UNKNOWN = -1
cc.CameraFlag = {
	USER5 = 32,
	USER4 = 16,
	USER3 = 8,
	USER2 = 4,
	USER1 = 2,
	USER8 = 256,
	DEFAULT = 1,
	USER7 = 128,
	USER6 = 64
}
cc.CameraBackgroundBrush.BrushType = {
	SKYBOX = 3,
	DEPTH = 1,
	COLOR = 2,
	NONE = 0
}
cc.BillBoard_Mode = {
	VIEW_POINT_ORIENTED = 0,
	VIEW_PLANE_ORIENTED = 1
}
cc.GLProgram_VERTEX_ATTRIB = {
	TEX_COORD2 = 4,
	TEX_COORD4 = 6,
	TEX_COORD = 2,
	TEX_COORD7 = 9,
	NORMAL = 10,
	COLOR = 1,
	POSITION = 0,
	TEX_COORD5 = 7,
	BLEND_WEIGHT = 11,
	BLEND_INDEX = 12,
	MAX = 13,
	TEX_COORD3 = 5,
	TEX_COORDS = 2,
	TEX_COORD6 = 8,
	TEX_COORD1 = 3
}
cc.MATRIX_STACK_TYPE = {
	MODELVIEW = 0,
	TEXTURE = 2,
	PROJECTION = 1
}
cc.LightType = {
	AMBIENT = 3,
	DIRECTIONAL = 0,
	SPOT = 2,
	POINT = 1
}
cc.LightFlag = {
	LIGHT0 = math.pow(2, 0),
	LIGHT1 = math.pow(2, 1),
	LIGHT2 = math.pow(2, 2),
	LIGHT3 = math.pow(2, 3),
	LIGHT4 = math.pow(2, 4),
	LIGHT5 = math.pow(2, 5),
	LIGHT6 = math.pow(2, 6),
	LIGHT7 = math.pow(2, 7),
	LIGHT8 = math.pow(2, 8),
	LIGHT9 = math.pow(2, 9),
	LIGHT10 = math.pow(2, 10),
	LIGHT11 = math.pow(2, 11),
	LIGHT12 = math.pow(2, 12),
	LIGHT13 = math.pow(2, 13),
	LIGHT14 = math.pow(2, 14),
	LIGHT15 = math.pow(2, 15)
}
cc.AsyncTaskPool.TaskType = {
	TASK_NETWORK = 1,
	TASK_OTHER = 2,
	TASK_IO = 0,
	TASK_MAX_TYPE = 3
}
cc.RED = cc.c3b(255, 0, 0)
cc.GREEN = cc.c3b(0, 255, 0)
cc.BLUE = cc.c3b(0, 0, 255)
cc.BLACK = cc.c3b(0, 0, 0)
cc.WHITE = cc.c3b(255, 255, 255)
cc.YELLOW = cc.c3b(255, 255, 0)
