local __FILE__ = select(1, ...) or ""
local __PACKAGE__ = string.gsub(__FILE__, "[^.]+$", "")

require(__PACKAGE__ .. "BattleSession")
require(__PACKAGE__ .. "sessions.StageBattleSession")
require(__PACKAGE__ .. "sessions.RTPVPBattleSession")
require(__PACKAGE__ .. "sessions.ArenaBattleSession")
require(__PACKAGE__ .. "sessions.TowerBattleSession")
require(__PACKAGE__ .. "sessions.CrusadeBattleSession")
require(__PACKAGE__ .. "sessions.SpStageBattleSession")
require(__PACKAGE__ .. "sessions.StagePracticeBattleSession")
require(__PACKAGE__ .. "sessions.HeroStoryBattleSession")
require(__PACKAGE__ .. "sessions.StageMazeBattleSession")
require(__PACKAGE__ .. "sessions.MazeFinalBossBattleSession")
require(__PACKAGE__ .. "sessions.ExploreBattleSession")
require(__PACKAGE__ .. "sessions.PetRaceBattleSession")
require(__PACKAGE__ .. "sessions.ActstageBattleSession")
require(__PACKAGE__ .. "sessions.ClubBattleSession")
require(__PACKAGE__ .. "sessions.DreamBattleSession")
require(__PACKAGE__ .. "sessions.CooperateBattleSession")
require(__PACKAGE__ .. "sessions.DumpBattleSession")
require(__PACKAGE__ .. "sessions.FakeBattleSession")
