require("dm.gameplay.base.IconFactory")
require("dm.gameplay.base.RuleFactory")
require("dm.gameplay.base.RoleFactory")
require("dm.gameplay.base.prototype.PrototypeFactory")
require("dm.gameplay.base.BattleLauncher")
require("dm.gameplay.base.BattleLoader")
